### ISSUE TITLE
No module named 'scripts' on Kali Linux

### ISSUE THREAD

**Issue by Teicu** [tijme/angularjs-csti-scanner#1]
Hello 
Can you help me solve this problem please

_acstis --uri="https://site.com/" --crawl
Traceback (most recent call last):
  File "/usr/local/bin/acstis", line 7, in <module>
    from scripts.acstis_cli import main
ImportError: No module named 'scripts'_ 

tester@kali:~# python
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux

**Comment by tijme** [comment]
Hi @Teicu,

Did you install ACSTIS using pip?

`apt-get install python3-pip`
`pip3 install --upgrade acstis`

Also make sure you have installed Google Chrome (the scanner uses Google Chrome to verify alert popups). I just tried installing ACSTIS on a Kali VM (downloaded from https://www.offensive-security.com/kali-linux-vmware-virtualbox-image-download/) and it worked for me.

If you have any more trouble, could you let me know?

**Comment by Teicu** [comment]
Hi Tijme,  

what about

_: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.9.0-kali3-amd64 x86_64)_

**Comment by tijme** [comment]
Do you have a display attached to your machine? The error occurs if there is no display attached. You could try using a virtual display using [XVFB](https://www.x.org/archive/X11R7.6/doc/man/man1/Xvfb.1.xhtml).

`apt-get install xvfb`
`export DISPLAY=:99.0`

You need to save [this](https://gist.github.com/jterrace/2911875) script to /etc/init.d/xvfb, then run this command:

`sh -e /etc/init.d/xvfb start`

**Comment by Teicu** [comment]
Hi, I'm sorry for delay
I'm on Macbook pro using kali linux from vmware fusion

**Comment by Teicu** [comment]
As you know kali linux don't have google chrome installed by default, so I installed it. But I still get this error 

_2017-06-02 05:37:35.454005: Started scan
2017-06-02 05:38:36.526408: Error while scraping URL 'https://test.com/': Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.9.0-kali3-amd64 x86_64)_ 


_~# google-chrome-stable --no-sandbox
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[10398:10398:0602/053714.355465:ERROR:gles2_cmd_decoder.cc(2475)] [GroupMarkerNotSet(crbug.com/242999)!:D0BCEE4359150000]GL ERROR :GL_INVALID_VALUE : BackFramebuffer::Create: <- error from previous GL command
[10398:10398:0602/053714.925676:ERROR:gles2_cmd_decoder.cc(2475)] [GroupMarkerNotSet(crbug.com/242999)!:D0C7274459150000]GL ERROR :GL_INVALID_VALUE : BackFramebuffer::Create: <- error from previous GL command_ 


http://i.imgur.com/TTw3guu.png

**Comment by tijme** [comment]
@Teicu Ah, I got the same error as in your printscreen. Please run this program as a non root user. The Chrome Driver won't allow it to run as root. I will fix this as soon as possible.

**Comment by tijme** [comment]
@Teicu Did you manage to get it working? 😃
