### ISSUE TITLE
[Feature Request] Log confirmed working payloads

### ISSUE THREAD

**Issue by random-robbie** [tijme/angularjs-csti-scanner#11]
Hi,

Can we add a logging feature of found urls that the XSS works on?

**Comment by tijme** [comment]
Thanks for the feature request. It seems possible to do this.

Maybe using an argument like ``-vrl [FILENAME]``,``--vulnerable-requests-log=[FILENAME]`` that logs all vulnerable requests to the ``[FILENAME]`` file.

------------------

In the mean time you can use ``python -u acstis.py > output.log`` and then search for ``vulnerable`` in the ``output.log``.

**Comment by random-robbie** [comment]
this would be perfect as i plan to to a mass scan of a lot of urls and need to be able to dump all the vulnerable urls.
