### ISSUE TITLE
Requirement issues

### ISSUE THREAD

**Issue by random-robbie** [tijme/angularjs-csti-scanner#13]
On a fresh machine when you do pip install -r requirements.txt

you get and this is the same on python 3 or python 2

```
Collecting sphinx-better-theme==0.13 (from nyawc==1.7.11->acstis==3.0.5)
  Could not find a version that satisfies the requirement sphinx-better-theme==0.13 (from nyawc==1.7.11->acstis==3.0.5) (from versions: 0.1, 0.1.4, 0.1.5)
No matching distribution found for sphinx-better-theme==0.13 (from nyawc==1.7.11->acstis==3.0.5)

```

**Comment by tijme** [comment]
Thank you for reporting the issue.

Somehow version `0.13` from the `sphinx-better-theme` package was deleted from the PyPi warehouse. I updated the package to the latest version and everything should be working like a charm now.

If you experience any problems, please let me know.
