### ISSUE TITLE
Parrot OS  can't find `__main__` module in `acstis`

### ISSUE THREAD

**Issue by sudosuperman** [tijme/angularjs-csti-scanner#2]
root@DESKTOP-URC8ANJ:/mnt/c/angularjs-csti-scanner-master# python acstis --url **************.com/
usr/bin/python: can't find '__main__' module in 'acstis'

**Comment by sudosuperman** [comment]
never mind, i was running cmd as admin on the windows bash

i got it working then ended up with this  


root@DESKTOP-URC8ANJ:/mnt/c/angularjs-csti-scanner-master# acstis --u https://*********.ca/ --crawl
AngularJS CSTI Scanner (ACSTIS)
Copyright (c) 2017 Tijme Gommers (see `LICENSE.md`).

2017-06-12 23:46:48.901820: Started scan
2017-06-12 23:46:48.940101: Error while scraping URL 'https://*********.ca/': Message: Service /usr/local/lib/python3.5/dist-packages/acstis/chrome_drivers/chromedriver_linux64 unexpectedly exited. Status code was: 127

root@DESKTOP-URC8ANJ:/mnt/c/angularjs-csti-scanner-master#

**Comment by tijme** [comment]
Hi @sudosuperman,

Thanks for reporting the issue. I've got a few questions.

* Did you install ACSTIS using pip(3)?
* Are you running Ubuntu headless?
* Could you give me the output of `echo $DISPLAY`?
  * If this is empty, could you try `export DISPLAY=:1` and run ACSTIS?
* Could you give me the output of `/usr/local/lib/python3.5/dist-packages/acstis/chrome_drivers/chromedriver_linux64 --version`?
* Could you give me the output of `uname -i`?

**Comment by sudosuperman** [comment]
im sorry for my lack of knowledge but im not sure what you mean by headless and yes im using pip3.

root@DESKTOP-URC8ANJ:/mnt/c# echo $DISPLAY
root@DESKTOP-URC8ANJ:/mnt/c# export DISPLAY=:1
root@DESKTOP-URC8ANJ:/mnt/c# /usr/local/lib/python3.5/dist-packages/acstis/chrome_drivers/chromedriver_linux64 --version/usr/local/lib/python3.5/dist-packages/acstis/chrome_drivers/chromedriver_linux64: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
root@DESKTOP-URC8ANJ:/mnt/c# sudo /usr/local/lib/python3.5/dist-packages/acstis/chrome_drivers/chromedriver_linux64 --version
/usr/local/lib/python3.5/dist-packages/acstis/chrome_drivers/chromedriver_linux64: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

root@DESKTOP-URC8ANJ:/mnt/c# uname -i
x86_64
root@DESKTOP-URC8ANJ:/mnt/c#

**Comment by sudosuperman** [comment]
i was missing libnss3 so i installed it... but same thing; unexpectedly exited. Status code was: 127

**Comment by tijme** [comment]
@sudosuperman You need Ubuntu desktop so you have a display server which Chrome can use. If you use Ubuntu server you need to install a virtual display server.

I just tested ACSTIS on Ubuntu Desktop (https://www.ubuntu.com/download/desktop). I installed Chrome, Python3 and Pip3. I then installed ACSTIS using `sudo pip3 install acstis`. This works for me.

What does `/usr/local/lib/python3.5/dist-packages/acstis/chrome_drivers/chromedriver_linux64 --version` output now?

**Comment by sudosuperman** [comment]
i have windows & pattot os dual boot.  will it work on parrot os because it is based on ubuntu and froxen box?

**Comment by tijme** [comment]
@sudosuperman Hmm, I have no idea.

Now that you have fixed the Chrome driver issue, could you send me this output once more? `/usr/local/lib/python3.5/dist-packages/acstis/chrome_drivers/chromedriver_linux64 --version`

And could you maybe run `chmod a+x /usr/local/lib/python3.5/dist-packages/acstis/chrome_drivers/chromedriver_linux64` and then try if ACSTIS works?

**Comment by sudosuperman** [comment]
i will do that tonight and i will let you know in the morning. thank you for your help and quick responses as well.

**Comment by sudosuperman** [comment]
hello, so i switched from my ubuntu based bash on windows 10 to my parrot OS, followed all the steps and i worked like a dream. thank you very much for your help.

**Comment by tijme** [comment]
Ok, good to hear you got it working!
