### ISSUE TITLE
[Feature Request] Add Cookie Header

### ISSUE THREAD

**Issue by fatihersinadim** [tijme/angularjs-csti-scanner#4]
Hi,

I think it would be very useful to users add custom HTTP Cookie header. This option can be used to specify how to connect to the target URL.

Thanks,

**Comment by tijme** [comment]
Thanks for the idea!

I am currently working on a complete refactor and I will implement authentication options like BasicAuth, OAuth and also custom headers.

I hope to have it ready in a few weeks 😄

**Comment by tijme** [comment]
@fatihersinadim I just released version [3.0.0](https://github.com/tijme/angularjs-csti-scanner/releases/tag/3.0.0). Cookies are now supported. Check the [README](https://github.com/tijme/angularjs-csti-scanner/blob/master/README.rst) for installation & usage instructions.
